# Generated by Django 4.2 on 2026-04-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('scholar_no', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
