# Generated by Django 4.2 on 2026-06-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_enrollment_no_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
