# Generated by Django 4.2 on 2026-06-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_post_likes_post_parent_post_post_saves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
